### ISSUE TITLE
Should avoid removing included by regClientScript html-portions

### ISSUE THREAD

**Issue by PatchRanger** [bezumkin/MinifyX#18]
### How to reproduce
Use `regClientScript` from any snippet to include any html-portion.

### Expected result
Included html-portion must appear at the page.

### Real result
It doesn't.

### Reason
During reacting on `OnWebPagePrerender` Minifyx doesn't handle html-portions, which causes just replacing them with minified `js` and `css`.

**Comment by sergant210** [comment]
Прикольно. А можешь то же, только по-китайски. Василий полиглот, разберется :)

**Comment by bezumkin** [comment]
Why do you think that **register client script** option **must** work with raw html?

MinifyX works with css, scss, less, coffee and js **files**.

**Comment by PatchRanger** [comment]
> Why do you think that register client script option must work with raw html?

Because `regClientScript` works with raw HTML and some extras/snippets rely on it - such behavior makes them misbehaving. I don't mean minifying or other processing - just skipping instead of silently erasing (replacing).

**Comment by PatchRanger** [comment]
@bezumkin Спасибо))
