### ISSUE TITLE
После обновления до 1.4.0 стили не компилируются

### ISSUE THREAD

**Issue by PatchRanger** [bezumkin/MinifyX#19]
### Как воспроизвести
Подключить less-файл с вложенными импортами как в #5 или с `z-index`.

### Ожидаемый результат
Стили скомпилировались, отобразилась нормальная "цветная" страница.

### Реальный результат
Страница "чёрно-белая" - только разметка, стили не подключились из-за ошибки компилятора, в логах наблюдаем:
``
[MinifyX] Error in LESS Compiler: parse error: failed at `z-index: +1;`
``

### Причины
Обновление `Munee` со всеми зависимостями привело к использованию другой версии CSS-компилятора [leafo/lessphp](https://github.com/leafo/lessphp). Судя по `core/components/minifyx/munee/composer/installed.json` у меня установилась `v0.4.0` (к слову, не самая свежая, есть `v0.5.0`). Компилятор (судя по заявкам) глючит: https://github.com/leafo/lessphp/issues/503, https://github.com/leafo/lessphp/issues/498 .
Похоже, мы с этим уже сталкивались: #9 - и тогда был заменён компилятор на `oyejorge/less.php`. Но щас, поскольку `MinfyX` теперь опирается на стороннюю библиотеку, которая использует официально неподдерживаемый (мёртвый) компилятор (см. https://github.com/leafo/lessphp/issues/543 ) решение не видится таким очевидным.

@bezumkin Василий, я вижу такие возможности:
- Либо с помощью манипуляций с подмодулем заставить `Munee` использовать какая была раньше, работающую версию `leafo/lessphp`.
- Либо оформить пулл-реквест в `Munee` с откатом к прежней версии `leafo/lessphp`. Довольно странно, что у меня установилась `v0.4.0`, хотя у `Munee` в `composer.json` указана `v0.5.0`.
- Либо оформить пулл-реквест в `Munee` с заменой `leafo/lessphp` на `oyejorge/less.php`. Этот вариант мне кажется предпочтительным, в силу того, что `leafo/lessphp` мёртв и не работает, а `oyejorge/less.php` - жив (поддерживается) и работает (я проверил: заменил в `core/components/minifyx/munee/composer/autoload_classmap.php` и `core/components/minifyx/munee/vendor/composer/autoload_classmap.php` пути к компилятору на путь к `oyejorge/less.php` - и страницы открываются как надо, стили компилируются). Смущает только то, что `Munee` не очень активно поддерживается, поэтому пулл-реквест может "зависнуть" неутверждённым (несмёрдженным), не решая проблемы.

Как вы считаете, какой вариант предпочтительнее? Что скажете?

**Comment by bezumkin** [comment]
Скажу, что внутри архива лежит lessphp 0.5.0 - в этом можно убедиться, открыв сам файл
[![](https://file.modx.pro/files/f/a/c/faca0595d5cf85fd96e6a6d6eec92ebas.jpg)](https://file.modx.pro/files/f/a/c/faca0595d5cf85fd96e6a6d6eec92eba.png)
> core/components/minifyx/munee/composer/installed.json

Такого файла в пакете и вовсе нет.

Пока снова заменил leafo/lessphp на oyejorge/less.php, но советую это всё же отправить в репозиторий Munee, а то потом опять забуду.

**Comment by PatchRanger** [comment]
> Скажу, что внутри архива лежит lessphp 0.5.0 - в этом можно убедиться, открыв сам файл

Точно, спасибо, судя по https://github.com/leafo/lessphp/commit/0f5a7f5545d2bcf4e9fad9a228c8ad89cc9aa283#commitcomment-9074087 алиас `dev-master` не обновлён, но это не повлияло на загружаемую версию, значит у меня тоже самая свежая.

> Пока снова заменил leafo/lessphp на oyejorge/less.php

Не вижу этого в коммите https://github.com/bezumkin/MinifyX/commit/2d1971b866a7811061be4d140440e59359f44e57 . Насколько я понял, глядя на https://github.com/bezumkin/MinifyX/tree/master/core/components/minifyx, `Munee` установлен как git-подмодуль, поэтому любые изменения в нём самом в основной репозиторий не коммитятся. Надо подмодуль в папку превратить: http://stackoverflow.com/a/1789374 - только надо иметь в виду, что это зафиксирует версию `Munee`, не будем обновления от него получать, мы по сути копию сделаем. Зато опять работать будет))

> Сейчас MinifyX 1.4.1-pl без проблем собирает Bootstrap 3.3.4.

Спасибо))

**Comment by bezumkin** [comment]
Нет, не хочу директорией.

Пусть пока будет так, с изменённым composer.json у меня на компе.
