### ISSUE TITLE
Stopped working after update to 1.4.3

### ISSUE THREAD

**Issue by dymitar** [bezumkin/MinifyX#22]
After update to 1.4.3 the component stopped working with following error:
<pre>
[Thu Apr 28 14:29:25.989085 2016] [:error] [pid 7765] [client 192.168.188.1:48576] PHP Warning:  Uncaught exception 'Sabberworm\\CSS\\Parsing\\UnexpectedTokenException' with message 'Search for \xe2\x80\x9cOne of ("{")\xe2\x80\x9d returned no results. Context: \xe2\x80\x9c\xe2\x80\x9d.' in /var/www/html/nit.bg/core/components/minifyx/munee/vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parser.php:578\nStack trace:\n#0 /var/www/html/nit.bg/core/components/minifyx/munee/vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parser.php(270): Sabberworm\\CSS\\Parser->consumeUntil('{', false, true)\n#1 /var/www/html/nit.bg/core/components/minifyx/munee/vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parser.php(95): Sabberworm\\CSS\\Parser->parseSelector()\n#2 /var/www/html/nit.bg/core/components/minifyx/munee/vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parser.php(78): Sabberworm\\CSS\\Parser->parseList(Object(Sabberworm\\CSS\\CSSList\\Document), true)\n#3 /var/www/html/nit.bg/core/components/minifyx/munee/vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parser.php(72): Sabberworm\\CSS\\Parser->parseDocument(Object(Sabberworm\\CSS\\CSSList\\Document) in /var/www/html/nit.bg/core/components/minifyx/munee/vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parser.php on line 578
[Thu Apr 28 14:29:25.989118 2016] [:error] [pid 7765] [client 192.168.188.1:48576] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/nit.bg/core/components/minifyx/munee/vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parser.php on line 96
</pre>
Reverting back to 1.4.2 fixes the problem.
Versions - ModX 2.5, PHP 5.5
Specifics - multilingual site with 2 contexts - english and bulgarian

**Comment by bezumkin** [comment]
I just updated https://github.com/sabberworm/PHP-CSS-Parser/ to 7.0.2 from 7.0.0 because of PHP 7.0 issues.

Works great on all my sites both on PHP 5.6 and 7.0.
